<?php

/**
 * TDProject_Webservice
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 */


$tasksObject = $this->getContext()->getAttribute('tasksObject');
?>
<h2><?php echo $this->getPageHeadline() ?></h2>
<h5><?php echo $this->getHeadline() ?></h5>


<ul>
<?php $this->displayTasks($tasksObject);?>
</ul>
