<?php

/**
 * TDProject_Webservice
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 */

$projects = $this->getContext()->getAttribute('projects');
$pageHeadline = $this->getContext()->getAttribute('pageHeadline');
$headline = $this->getContext()->getAttribute('headline');


?>
<h2>
<?php echo $this->getPageHeadline() ?></h2>
<h5>
<?php echo $this->getHeadline() ?></h5>
<form action="<?php echo $this->getUrl(); ?>" method="post">
	<input type="hidden" name="path" value="/webservice">
	<input type="hidden" name="method" value="login">
	<table>
		<tr>
			<th><label for="userName">userName:</label>
			</th>
			<td><input type="text" name="userName" id="userName" size="20">
			</td>
		</tr>
		<tr>
			<th><label for="password">password:</label>
			</th>
			<td><input type="password" name="password" id="password" size="20">
			</td>
		</tr>
		<tr>
			<td></td>
			<td><input type="submit">
			</td>
		</tr>
	</table>
</form>


<?php /*?>
<form
action="<?php echo $this->getUrl(); ?>"
method="post">
<input type="hidden" name="path" value="/webservice">
<table>
<tr>
<th><label for="method">option:</label>
</th>
<td><select name=method id="method">
<option>loadLoggings</option>
<option>loadProjects</option>
</select>
</td>
</tr>
<tr>
<th><label for="userName">userName:</label>
</th>
<td><input type="text" name="userName" id="userName" size="20">
</td>
</tr>
<tr>
<th><label for="userId">userId:</label>
</th>
<td><input type="text" name="userId" id="userId" size="4">
</td>
</tr>
<tr>
			<td></td>
			<td><input type="submit">
			</td>
		</tr>
	</table>
</form>
*/
