<?php

/**
 * TDProject_Webservice
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 */


//get the Zend_Soap_Server-instance from the request
$result =
$this->getContext()->getAttribute(TDProject_Webservice_Controller_Util_WebRequestKeys::SOAP_SERVER);

//let the instance handle the requests
echo $result;