<?php

/**
 * TDProject_Webservice
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 */


//get Zend_Soap_AutoDiscover-instance
$autoDiscover = $this->getContext()->getAttribute(
    TDProject_Webservice_Controller_Util_WebRequestKeys::AUTO_DISCOVER
);
//use handle-method to send headers and display the wsdl-xml
$autoDiscover->handle();